services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    environment:
      USER_UID: "${PUID}"
      USER_GID: "${PGID}"
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3002:3000"
      - "222:22"
    networks:
      - homelab

networks:
  homelab:
    external: true

volumes:
  gitea_data:
