services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf
    container_name: stirling-pdf
    restart: unless-stopped
    environment:
      DOCKER_ENABLE_SECURITY: "false"
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - stirling_configs:/configs
      - stirling_data:/usr/share/tessdata
    ports:
      - "8087:8080"
    networks:
      - homelab

networks:
  homelab:
    external: true

volumes:
  stirling_configs:
  stirling_data:
