services:
  linkding:
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.linkding.rule=Host(`linkding.${DOMAIN}`)"
      - "traefik.http.routers.linkding.entrypoints=websecure"
      - "traefik.http.routers.linkding.tls=true"
      - "traefik.http.routers.linkding.tls.certresolver=cloudflare"
      - "traefik.http.services.linkding.loadbalancer.server.port=9090"

networks:
  traefik_proxy:
    external: true
